[Definition]
# Traefik access log format:
# <IP> - - [date] "METHOD /path HTTP/x" STATUS bytes "-" "UA" N "router" "service" Xms
failregex = ^<HOST> .+ "(POST|GET|PUT|DELETE|PATCH) .+ HTTP/\d" (401|403|429) .+$
ignoreregex =
