[traefik-auth]
enabled  = true
port     = http,https
filter   = traefik
logpath  = /var/log/traefik/access.log
# Ban si 10 erreurs 401/403/429 en 60 secondes
maxretry = 10
findtime = 60
# Ban de 1 heure
bantime  = 3600
